package vistas;

import accesoADatos.MembresiaData;
import accesoADatos.SocioData;
import entidades.Membresia;
import entidades.Socio;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author elise
 */
public class FormularioAgregarMembresia extends javax.swing.JInternalFrame {

    private MembresiaData membresiad;
    private Membresia membresia = null;
    private SocioData sociod;
    private Socio socio = null;

    /**
     * Creates new form FormularioAgregarMembresia
     */
    public FormularioAgregarMembresia() {
        initComponents();
        membresiad = new MembresiaData();
        sociod = new SocioData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTFDNISocio = new javax.swing.JTextField();
        jTFPases = new javax.swing.JTextField();
        jTFCostos = new javax.swing.JTextField();
        jLDNISocio = new javax.swing.JLabel();
        jLPases = new javax.swing.JLabel();
        jLFechaInicio = new javax.swing.JLabel();
        jLAgregarMembresia = new javax.swing.JLabel();
        jBAgregar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jLCostos = new javax.swing.JLabel();
        jDCFechaInicio = new com.toedter.calendar.JDateChooser();

        jLDNISocio.setText("DNI Socio");

        jLPases.setText("Pases");

        jLFechaInicio.setText("Fecha Inicio");

        jLAgregarMembresia.setText("Agregar Membresia");

        jBAgregar.setText("Agregar");

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jLCostos.setText("Costos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLAgregarMembresia))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLDNISocio)
                                    .addComponent(jLPases))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFPases)
                                    .addComponent(jTFDNISocio)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLCostos)
                                    .addComponent(jLFechaInicio))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jDCFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 109, Short.MAX_VALUE))
                                    .addComponent(jTFCostos)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBSalir)))))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLAgregarMembresia)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLDNISocio)
                    .addComponent(jTFDNISocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFPases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLPases))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCostos)
                    .addComponent(jTFCostos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLFechaInicio)
                    .addComponent(jDCFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAgregar)
                    .addComponent(jBSalir))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
        String dni = jTFDNISocio.getText();
        socio = sociod.buscarSocioPorDni(dni);
        int pases = Integer.parseInt(jTFPases.getText());
        double costos = Double.parseDouble(jTFCostos.getText());
        java.util.Date fechaInicio = jDCFechaInicio.getDate();
        LocalDate fecha = fechaInicio.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate fechaFin = fecha.plusDays(30);
        membresia = new Membresia();
        membresia.setSocio(socio);
        membresia.setCantidadPases(pases);
        membresia.setCosto(costos);
        membresia.setFechaInicio(fecha);
        membresia.setFechaFin(fechaFin);
        membresiad.agregarMembresia(membresia);

    }//GEN-LAST:event_jBAgregarActionPerformed

    private void limpiarCampos() {
        jTFDNISocio.setText("");
        jTFPases.setText("");
        jTFCostos.setText("");
        jDCFechaInicio.setDate(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBSalir;
    private com.toedter.calendar.JDateChooser jDCFechaInicio;
    private javax.swing.JLabel jLAgregarMembresia;
    private javax.swing.JLabel jLCostos;
    private javax.swing.JLabel jLDNISocio;
    private javax.swing.JLabel jLFechaInicio;
    private javax.swing.JLabel jLPases;
    private javax.swing.JTextField jTFCostos;
    private javax.swing.JTextField jTFDNISocio;
    private javax.swing.JTextField jTFPases;
    // End of variables declaration//GEN-END:variables
}
