/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import accesoADatos.Conexion;
import accesoADatos.EntrenadorData;
import entidades.Entrenador;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nn
 */
public class FormularioListasDeEntrenadores extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo;
    private Connection con = null;
    public FormularioListasDeEntrenadores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCBEspecialidades = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT = new javax.swing.JTable();
        jBBuscar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jLabel1.setText("Listas de Entrenadores");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setText("Listar Por:");

        jCBEspecialidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBEspecialidades.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBEspecialidadesItemStateChanged(evt);
            }
        });

        jT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jT);

        jBBuscar.setText("Listar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBEspecialidades, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCBEspecialidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBEspecialidadesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBEspecialidadesItemStateChanged
    llenarComboBoxEspecialidades();
    
    }//GEN-LAST:event_jCBEspecialidadesItemStateChanged

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
       String especialidadSeleccionada = (String) jCBEspecialidades.getSelectedItem();
       llenarTablaConEntrenadores(especialidadSeleccionada);
    }//GEN-LAST:event_jBBuscarActionPerformed
     
    private void llenarTablaConEntrenadores(String especialidad) {
   
    EntrenadorData entrenadorData = new EntrenadorData(); 
    List<Entrenador> entrenadores = entrenadorData.buscarEntrenadorPorEspecialidad(especialidad);
    
    
    limpiarTabla();
    
    DefaultTableModel modelo = (DefaultTableModel) jT.getModel();
    for (Entrenador entrenador : entrenadores) {
        Object[] fila = {entrenador.getIdEntrenador(), entrenador.getDni(), entrenador.getNombre(), entrenador.getApellido(), entrenador.getEspecialidad()};
        modelo.addRow(fila);
    }
}
    private void limpiarTabla() {
    DefaultTableModel modelo = (DefaultTableModel) jT.getModel();
    modelo.setRowCount(0);
}
    private void llenarComboBoxEspecialidades() {
     
        limpiarItemsComboBox();
        List<String> especialidades = listarEspecialidades();
        for (String especialidad : especialidades) {
            jCBEspecialidades.addItem(especialidad);
        }
    }
    
    private void limpiarItemsComboBox() {

        for (int i = jCBEspecialidades.getItemCount() - 1; i >= 0; i--) {
            jCBEspecialidades.removeItemAt(i);
        }
    }
     
     public List<String> listarEspecialidades(){
     ArrayList<String> especialidades = new ArrayList<>();
     String sql = "SELECT DISTINCT especialidad FROM entrenador WHERE estado = 1";
        try{
            
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
            String especialidad = rs.getString("especialidad");
            especialidades.add(especialidad);
            
            }
            ps.close();
        
        }catch(SQLException ex){
        JOptionPane.showMessageDialog(null, "error al acceder a la tabla");
            System.out.println(ex.getMessage());
        }
        return especialidades;
     
     }
      public void armarCabecera() {
        modelo.addColumn("idEntrenador");
        modelo.addColumn("Dni");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Especialidad");
        jT.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JComboBox<String> jCBEspecialidades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jT;
    // End of variables declaration//GEN-END:variables
}
