package vistas;

import accesoADatos.MembresiaData;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author elise
 */
public class GymG6 extends javax.swing.JFrame {

    MembresiaData membresiaData;

    /**
     * Creates new form GymG6
     */
    public GymG6() {
        initComponents();
        membresiaData = new MembresiaData();
        membresiaData.modificarMembresiasVencidas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/recursos/gym3.jpg"));
        Image image = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);}};
        jMenuBar1 = new javax.swing.JMenuBar();
        jMSocio = new javax.swing.JMenu();
        jMClases = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMEntrenadores = new javax.swing.JMenu();
        jMIListarEntrenadores = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMMembresia = new javax.swing.JMenu();
        jMIFormularioMembresia = new javax.swing.JMenuItem();
        jMIAgregarMembresia = new javax.swing.JMenuItem();
        jMAsistencias = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 700));

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        jMenuBar1.setToolTipText("");

        jMSocio.setText("Socio");
        jMSocio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMSocioMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMSocio);

        jMClases.setText("Clases");

        jMenuItem1.setText("Buscar Clases");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMClases.add(jMenuItem1);

        jMenuItem2.setText("Agregar Clase");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMClases.add(jMenuItem2);

        jMenuBar1.add(jMClases);

        jMEntrenadores.setText("Entrenadores");

        jMIListarEntrenadores.setText("Listas de Entrenadores");
        jMIListarEntrenadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIListarEntrenadoresActionPerformed(evt);
            }
        });
        jMEntrenadores.add(jMIListarEntrenadores);

        jMenuItem3.setText("Formulario Entrenadores");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMEntrenadores.add(jMenuItem3);

        jMenuBar1.add(jMEntrenadores);

        jMMembresia.setText("Membresia");

        jMIFormularioMembresia.setText("Historial Membresia");
        jMIFormularioMembresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIFormularioMembresiaActionPerformed(evt);
            }
        });
        jMMembresia.add(jMIFormularioMembresia);

        jMIAgregarMembresia.setText("Agregar Membresia");
        jMIAgregarMembresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAgregarMembresiaActionPerformed(evt);
            }
        });
        jMMembresia.add(jMIAgregarMembresia);

        jMenuBar1.add(jMMembresia);

        jMAsistencias.setText("Asistencias");
        jMAsistencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMAsistenciasMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMAsistencias);

        jMenu1.setText("Salir");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );

        jDesktopPane1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        BuscarClase buscarClase = new BuscarClase();
        buscarClase.setVisible(true);
        jDesktopPane1.add(buscarClase);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        FormularioAgregarClase agreModifClase = new FormularioAgregarClase();
        agreModifClase.setVisible(true);
        jDesktopPane1.add(agreModifClase);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMSocioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMSocioMouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        FormularioSocio formSocio = new FormularioSocio();
        formSocio.setVisible(true);
        jDesktopPane1.add(formSocio);
    }//GEN-LAST:event_jMSocioMouseClicked

    private void jMAsistenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMAsistenciasMouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        FormularioAsistencias formAsistencia = new FormularioAsistencias();
        formAsistencia.setVisible(true);
        jDesktopPane1.add(formAsistencia);
    }//GEN-LAST:event_jMAsistenciasMouseClicked

    private void jMIFormularioMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIFormularioMembresiaActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        FormularioMembresia formMembresia = new FormularioMembresia();
        formMembresia.setVisible(true);
        jDesktopPane1.add(formMembresia);
    }//GEN-LAST:event_jMIFormularioMembresiaActionPerformed

    private void jMIAgregarMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAgregarMembresiaActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        FormularioAgregarMembresia membresia = new FormularioAgregarMembresia();
        membresia.setVisible(true);
        jDesktopPane1.add(membresia);
    }//GEN-LAST:event_jMIAgregarMembresiaActionPerformed

    private void jMIListarEntrenadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIListarEntrenadoresActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        FormularioListasDeEntrenadores formMateria = new FormularioListasDeEntrenadores();
        formMateria.setVisible(true);
        jDesktopPane1.add(formMateria);


    }//GEN-LAST:event_jMIListarEntrenadoresActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        FormularioEntrenadores formentrena = new FormularioEntrenadores();
        formentrena.setVisible(true);
        jDesktopPane1.add(formentrena);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GymG6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GymG6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GymG6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GymG6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GymG6().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMAsistencias;
    private javax.swing.JMenu jMClases;
    private javax.swing.JMenu jMEntrenadores;
    private javax.swing.JMenuItem jMIAgregarMembresia;
    private javax.swing.JMenuItem jMIFormularioMembresia;
    private javax.swing.JMenuItem jMIListarEntrenadores;
    private javax.swing.JMenu jMMembresia;
    private javax.swing.JMenu jMSocio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
